module Jekyll
  class OSSStoriesTagPageGenerator < Generator
    safe true
    priority :low

    def generate(site)
      # Check if tag layout exists (it should be defined in the theme)
      return unless site.layouts.key? 'tag'
      
      # Collect all tags from posts (handled by jekyll-archives)
      post_tags = site.tags.keys
      
      # Collect all tags from oss_stories
      oss_tags = []
      if site.collections['oss_stories']
        site.collections['oss_stories'].docs.each do |story|
          if story.data['tags']
            oss_tags.concat(story.data['tags'])
          end
        end
        oss_tags.uniq!
      end
      
      # Find tags that exist ONLY in oss_stories (not in posts)
      # These won't have pages generated by jekyll-archives, so we need to create them
      oss_only_tags = oss_tags - post_tags
      
      # Generate a page for each oss-only tag
      oss_only_tags.each do |tag|
        site.pages << TagPage.new(site, site.source, tag)
      end
    end
  end

  class TagPage < Page
    def initialize(site, base, tag)
      @site = site
      @base = base
      @dir  = File.join('tags', Jekyll::Utils.slugify(tag))
      @name = 'index.html'

      self.process(@name)
      
      # Set the layout and data directly without trying to read a file
      self.data = {
        'layout' => 'tag',
        'type' => 'tag',
        'title' => tag,
        'posts' => []  # Empty posts array since jekyll-archives doesn't handle this tag
      }
      
      self.content = ''
    end
  end
end