name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["production"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ruby with ruby-build
        run: |
          sudo apt-get update && sudo apt-get install -y git curl autoconf bison build-essential \
            libssl-dev libyaml-dev libreadline-dev zlib1g-dev libncurses5-dev \
            libffi-dev libgdbm6 libgdbm-dev
          git clone https://github.com/rbenv/ruby-build.git
          sudo ./ruby-build/install.sh
          ruby-build 3.3.4 /opt/ruby
          echo "/opt/ruby/bin" >> $GITHUB_PATH
          ruby --version
      
      - name: Setup Bundler
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
